name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create fake keystore properties
        run: |
          echo "storeFile=fake" > keystore.properties
          echo "storePassword=fake" >> keystore.properties
          echo "keyAlias=fake" >> keystore.properties
          echo "keyPassword=fake" >> keystore.properties
          if [ -d "app" ]; then
            cp keystore.properties app/keystore.properties
          fi


      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fixed-mod-apk
          path: "**/build/outputs/apk/debug/*.apk"
